conf = {
    'fx': 517.3,
    'fy': 516.5,
    'cx': 325.1,
    'cy': 249.7,
    'scale': 5000,
    'scale_factor': 1.2,
    'input_shape': (480, 640, 3),
    'batch_size': 4,
    'data_path': ['./datasets/freiburg1xyz/',
                  './datasets/freiburg2xyz/',
                  './datasets/freiburg3/',
                  ],
    'weights': './weights/best.h5',
    'resnet_weights': './weights/resnet50_notop.h5',
}
